### ISSUE TITLE
Cannot find diamond output 

### ISSUE THREAD

**Issue by ChristianFurbo** [qichao1984/NCyc#10]
Hi. :) 
I am trying to run the following:

 perl NCycProfiler.PL -d ~/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces -m diamond -f fasta -s prot -si /home/christian/Bioinformatic_programs/NCyc-master/FileForNcyc.txt -o PC_Ncyc

However, I get the following error: 

cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10786.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10787.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10788.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10789.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10790.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10791.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10792.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10793.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10794.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10795.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10796.diamond': No such file or directory
cp: cannot stat '/home/christian/Desktop/scripts_to_abacus/From_abacus/PC_AA_Seqeunces/AAsequencesF10797.diamond': No such file or directory
 was not found in /home/christian/Bioinformatic_programs/NCyc-master/FileForNcyc.txt, please check!

My tab delimited file looks like this:
head FileForNcyc.txt 
AAsequencesF10786	18190
AAsequencesF10787	10828
AAsequencesF10788	41144
AAsequencesF10789	44519
AAsequencesF10790	874
AAsequencesF10791	81255
AAsequencesF10792	61666
AAsequencesF10793	79880
AAsequencesF10794	63433
AAsequencesF10795	51039

Maybe, the problem is trivial, however I cant see how to fix it? :) 
Also, I tried with usearch, got the same problem

Cheers

**Comment by qichao1984** [comment]
Hi, two quick questions: Have you installed diamond in your linux system? Have you modified the perl script to include the correct path of diamond? If not, can you try that?
________________________________

**Comment by ChristianFurbo** [comment]
Hi. 
You were right. Something with the installation went wrong and tried to reinstall it. This time I used bioconda to install it. Modified the perl script with the new path for diamond. It worked and got the profile. :)
