### ISSUE TITLE
-si file: There is always a missing sample name after alignment ending

### ISSUE THREAD

**Issue by MaryoHg** [qichao1984/NCyc#11]
Dear @qichao1984 

Thanks for the NCyc. This is me asking for guidance.

I'm using your script as follows:
`$ perl NCycProfiler.pl -d ~/sickle/. -m diamond -f fastq -s nucl -si ~/sickle/samples.tsv -o ~/nitro_genes.tsv`

After running, i get the following:

>[...] Loading reference sequences...  [1.2e-05s]
Deallocating buffers...  [0.014192s]
Deallocating queries...  [0.028869s]
Loading query sequences...  [1e-05s]
Closing the input file...  [7e-06s]
Closing the output file...  [4.3e-05s]
Closing the database file...  [5e-06s]
Deallocating taxonomy...  [3e-06s]
Total time = 150.442s
Reported 153742 pairwise alignments, 153742 HSPs.
153742 queries aligned.
RP_IV_2 was not found in ~/sickle/samples.tsv, please check!

I tried running just two samples (two file names with their seqs counts in `samples.tsv`), though I got the same ¡error!

## Information about samples.tsv
--> I have 10 fastq files in ~/sickle/. Those fastq files are listed in `samples.tsv` without the file extension, and their seq counts each. Values are \t separated. 

So, Would you mind give a hand?

Thanks.
MaryoHg.

**Comment by qichao1984** [comment]
Hi Maryo, can you send your samples.tsv file? I'm doubting a format issue in the file, but not so sure before seeing the file.
________________________________

**Comment by MaryoHg** [comment]
@qichao1984 

I ran the following command to create the file with sample names:
`$ ls ~/sickle/*.fastq > samples.tsv`

Then I did the following:
1. Manually edited the extension name (deleting the pattern ".fastq") using gedit.
2. Used the `count_seqs.py` command in QIIME to know the seqs counts for each file and then I added a new column to the `samples.tsv` file.

You can see/download the file [here](https://drive.google.com/open?id=0BzdyY8HhOwC-SUVQcVlKQ1EyT0wtSzNqbF9GazlVVGN5S21Z).
If not enough, may I ask for an e-mail account to send it?


Thank you very much @qichao1984.

**Comment by qichao1984** [comment]
Maryo, the link seems not working to me. Please send it to tuqichao@outlook.com. Thanks!


________________________________

**Comment by MaryoHg** [comment]
Thanks @qichao1984.

I sent the file.

MaryoHg.

**Comment by MaryoHg** [comment]
Dear @qichao1984.

Just to let you know we were able to run `NCyc` in batch of five fastq samples. We are still unaware what is going on. 
We used the exactly same script but failed when running on all 10 fastq metagenome files. Twice, when the 10 fastq file ran, the output was filled with zeros.

We'll try to find out later.

Thanks for `NCyc` and your response.


MaryoHg.

**Comment by Rob-murphys** [comment]
What was the solution to this? I get the same error on every run of NCyc:

`ESC[0;39m was not found in /path/to/si/file/Green_500bp_filterd_dereplicated_prodigal_seqnum.txt, please check!`
